name: ppi_tiongkok
description: PPI Tiongkok Mobile Application

dependencies:
  flutter:
    sdk: flutter

  fluro: ^1.3.4
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.2.2
  transparent_image: ^0.1.0
  flutter_webview_plugin: ^0.2.1+2
  url_launcher: ^4.0.0
  flutter_full_pdf_viewer: ^1.0.1
  path_provider: ^0.4.1
  mailer: ^2.0.1
  flutter_spinkit: "^2.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/logo.jpg
    - res/djauharioratmangun.jpg
    - res/fadlanmuzakki.png
    - assets/img/mars.png
    - assets/img/neptune.png
    - assets/img/moon.png
    - assets/img/earth.png
    - assets/img/mercury.png
    - assets/img/no_image.jpg
    - assets/pdf/ADART.pdf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
